[package]
name = "hello_world"
version = "0.1.0"
authors = ["tux"]
edition = "2018"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
